#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "file.pb.h"

namespace webdisk
{

namespace FileService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void FileQuery(FileQueryReq *request, FileQueryResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void FileUpload(FileUploadReq *request, FileUploadResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void UploadInit(UploadInitReq *request, UploadInitResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void UploadChunk(UploadChunkReq *request, UploadChunkResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void UploadComplete(UploadCompleteReq *request, UploadCompleteResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void UploadStatus(UploadStatusReq *request, UploadStatusResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void FileDownload(FileDownloadReq *request, FileDownloadResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void FileDelete(FileDeleteReq *request, FileDeleteResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void FileRename(FileRenameReq *request, FileRenameResp *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using FileQueryDone = std::function<void (FileQueryResp *, srpc::RPCContext *)>;
using FileUploadDone = std::function<void (FileUploadResp *, srpc::RPCContext *)>;
using UploadInitDone = std::function<void (UploadInitResp *, srpc::RPCContext *)>;
using UploadChunkDone = std::function<void (UploadChunkResp *, srpc::RPCContext *)>;
using UploadCompleteDone = std::function<void (UploadCompleteResp *, srpc::RPCContext *)>;
using UploadStatusDone = std::function<void (UploadStatusResp *, srpc::RPCContext *)>;
using FileDownloadDone = std::function<void (FileDownloadResp *, srpc::RPCContext *)>;
using FileDeleteDone = std::function<void (FileDeleteResp *, srpc::RPCContext *)>;
using FileRenameDone = std::function<void (FileRenameResp *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void FileQuery(const FileQueryReq *req, FileQueryDone done);
	void FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> async_FileQuery(const FileQueryReq *req);

	void FileUpload(const FileUploadReq *req, FileUploadDone done);
	void FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> async_FileUpload(const FileUploadReq *req);

	void UploadInit(const UploadInitReq *req, UploadInitDone done);
	void UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> async_UploadInit(const UploadInitReq *req);

	void UploadChunk(const UploadChunkReq *req, UploadChunkDone done);
	void UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> async_UploadChunk(const UploadChunkReq *req);

	void UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done);
	void UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> async_UploadComplete(const UploadCompleteReq *req);

	void UploadStatus(const UploadStatusReq *req, UploadStatusDone done);
	void UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> async_UploadStatus(const UploadStatusReq *req);

	void FileDownload(const FileDownloadReq *req, FileDownloadDone done);
	void FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> async_FileDownload(const FileDownloadReq *req);

	void FileDelete(const FileDeleteReq *req, FileDeleteDone done);
	void FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> async_FileDelete(const FileDeleteReq *req);

	void FileRename(const FileRenameReq *req, FileRenameDone done);
	void FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> async_FileRename(const FileRenameReq *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_FileQuery_task(FileQueryDone done);
	srpc::SRPCClientTask *create_FileUpload_task(FileUploadDone done);
	srpc::SRPCClientTask *create_UploadInit_task(UploadInitDone done);
	srpc::SRPCClientTask *create_UploadChunk_task(UploadChunkDone done);
	srpc::SRPCClientTask *create_UploadComplete_task(UploadCompleteDone done);
	srpc::SRPCClientTask *create_UploadStatus_task(UploadStatusDone done);
	srpc::SRPCClientTask *create_FileDownload_task(FileDownloadDone done);
	srpc::SRPCClientTask *create_FileDelete_task(FileDeleteDone done);
	srpc::SRPCClientTask *create_FileRename_task(FileRenameDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void FileQuery(const FileQueryReq *req, FileQueryDone done);
	void FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> async_FileQuery(const FileQueryReq *req);

	void FileUpload(const FileUploadReq *req, FileUploadDone done);
	void FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> async_FileUpload(const FileUploadReq *req);

	void UploadInit(const UploadInitReq *req, UploadInitDone done);
	void UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> async_UploadInit(const UploadInitReq *req);

	void UploadChunk(const UploadChunkReq *req, UploadChunkDone done);
	void UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> async_UploadChunk(const UploadChunkReq *req);

	void UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done);
	void UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> async_UploadComplete(const UploadCompleteReq *req);

	void UploadStatus(const UploadStatusReq *req, UploadStatusDone done);
	void UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> async_UploadStatus(const UploadStatusReq *req);

	void FileDownload(const FileDownloadReq *req, FileDownloadDone done);
	void FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> async_FileDownload(const FileDownloadReq *req);

	void FileDelete(const FileDeleteReq *req, FileDeleteDone done);
	void FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> async_FileDelete(const FileDeleteReq *req);

	void FileRename(const FileRenameReq *req, FileRenameDone done);
	void FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> async_FileRename(const FileRenameReq *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_FileQuery_task(FileQueryDone done);
	srpc::SRPCHttpClientTask *create_FileUpload_task(FileUploadDone done);
	srpc::SRPCHttpClientTask *create_UploadInit_task(UploadInitDone done);
	srpc::SRPCHttpClientTask *create_UploadChunk_task(UploadChunkDone done);
	srpc::SRPCHttpClientTask *create_UploadComplete_task(UploadCompleteDone done);
	srpc::SRPCHttpClientTask *create_UploadStatus_task(UploadStatusDone done);
	srpc::SRPCHttpClientTask *create_FileDownload_task(FileDownloadDone done);
	srpc::SRPCHttpClientTask *create_FileDelete_task(FileDeleteDone done);
	srpc::SRPCHttpClientTask *create_FileRename_task(FileRenameDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void FileQuery(const FileQueryReq *req, FileQueryDone done);
	void FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> async_FileQuery(const FileQueryReq *req);

	void FileUpload(const FileUploadReq *req, FileUploadDone done);
	void FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> async_FileUpload(const FileUploadReq *req);

	void UploadInit(const UploadInitReq *req, UploadInitDone done);
	void UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> async_UploadInit(const UploadInitReq *req);

	void UploadChunk(const UploadChunkReq *req, UploadChunkDone done);
	void UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> async_UploadChunk(const UploadChunkReq *req);

	void UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done);
	void UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> async_UploadComplete(const UploadCompleteReq *req);

	void UploadStatus(const UploadStatusReq *req, UploadStatusDone done);
	void UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> async_UploadStatus(const UploadStatusReq *req);

	void FileDownload(const FileDownloadReq *req, FileDownloadDone done);
	void FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> async_FileDownload(const FileDownloadReq *req);

	void FileDelete(const FileDeleteReq *req, FileDeleteDone done);
	void FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> async_FileDelete(const FileDeleteReq *req);

	void FileRename(const FileRenameReq *req, FileRenameDone done);
	void FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> async_FileRename(const FileRenameReq *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_FileQuery_task(FileQueryDone done);
	srpc::BRPCClientTask *create_FileUpload_task(FileUploadDone done);
	srpc::BRPCClientTask *create_UploadInit_task(UploadInitDone done);
	srpc::BRPCClientTask *create_UploadChunk_task(UploadChunkDone done);
	srpc::BRPCClientTask *create_UploadComplete_task(UploadCompleteDone done);
	srpc::BRPCClientTask *create_UploadStatus_task(UploadStatusDone done);
	srpc::BRPCClientTask *create_FileDownload_task(FileDownloadDone done);
	srpc::BRPCClientTask *create_FileDelete_task(FileDeleteDone done);
	srpc::BRPCClientTask *create_FileRename_task(FileRenameDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void FileQuery(const FileQueryReq *req, FileQueryDone done);
	void FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> async_FileQuery(const FileQueryReq *req);

	void FileUpload(const FileUploadReq *req, FileUploadDone done);
	void FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> async_FileUpload(const FileUploadReq *req);

	void UploadInit(const UploadInitReq *req, UploadInitDone done);
	void UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> async_UploadInit(const UploadInitReq *req);

	void UploadChunk(const UploadChunkReq *req, UploadChunkDone done);
	void UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> async_UploadChunk(const UploadChunkReq *req);

	void UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done);
	void UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> async_UploadComplete(const UploadCompleteReq *req);

	void UploadStatus(const UploadStatusReq *req, UploadStatusDone done);
	void UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> async_UploadStatus(const UploadStatusReq *req);

	void FileDownload(const FileDownloadReq *req, FileDownloadDone done);
	void FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> async_FileDownload(const FileDownloadReq *req);

	void FileDelete(const FileDeleteReq *req, FileDeleteDone done);
	void FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> async_FileDelete(const FileDeleteReq *req);

	void FileRename(const FileRenameReq *req, FileRenameDone done);
	void FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> async_FileRename(const FileRenameReq *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_FileQuery_task(FileQueryDone done);
	srpc::TRPCClientTask *create_FileUpload_task(FileUploadDone done);
	srpc::TRPCClientTask *create_UploadInit_task(UploadInitDone done);
	srpc::TRPCClientTask *create_UploadChunk_task(UploadChunkDone done);
	srpc::TRPCClientTask *create_UploadComplete_task(UploadCompleteDone done);
	srpc::TRPCClientTask *create_UploadStatus_task(UploadStatusDone done);
	srpc::TRPCClientTask *create_FileDownload_task(FileDownloadDone done);
	srpc::TRPCClientTask *create_FileDelete_task(FileDeleteDone done);
	srpc::TRPCClientTask *create_FileRename_task(FileRenameDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void FileQuery(const FileQueryReq *req, FileQueryDone done);
	void FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> async_FileQuery(const FileQueryReq *req);

	void FileUpload(const FileUploadReq *req, FileUploadDone done);
	void FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> async_FileUpload(const FileUploadReq *req);

	void UploadInit(const UploadInitReq *req, UploadInitDone done);
	void UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> async_UploadInit(const UploadInitReq *req);

	void UploadChunk(const UploadChunkReq *req, UploadChunkDone done);
	void UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> async_UploadChunk(const UploadChunkReq *req);

	void UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done);
	void UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> async_UploadComplete(const UploadCompleteReq *req);

	void UploadStatus(const UploadStatusReq *req, UploadStatusDone done);
	void UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> async_UploadStatus(const UploadStatusReq *req);

	void FileDownload(const FileDownloadReq *req, FileDownloadDone done);
	void FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> async_FileDownload(const FileDownloadReq *req);

	void FileDelete(const FileDeleteReq *req, FileDeleteDone done);
	void FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> async_FileDelete(const FileDeleteReq *req);

	void FileRename(const FileRenameReq *req, FileRenameDone done);
	void FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> async_FileRename(const FileRenameReq *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_FileQuery_task(FileQueryDone done);
	srpc::TRPCHttpClientTask *create_FileUpload_task(FileUploadDone done);
	srpc::TRPCHttpClientTask *create_UploadInit_task(UploadInitDone done);
	srpc::TRPCHttpClientTask *create_UploadChunk_task(UploadChunkDone done);
	srpc::TRPCHttpClientTask *create_UploadComplete_task(UploadCompleteDone done);
	srpc::TRPCHttpClientTask *create_UploadStatus_task(UploadStatusDone done);
	srpc::TRPCHttpClientTask *create_FileDownload_task(FileDownloadDone done);
	srpc::TRPCHttpClientTask *create_FileDelete_task(FileDeleteDone done);
	srpc::TRPCHttpClientTask *create_FileRename_task(FileRenameDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("webdisk.FileService")
{
	this->srpc::RPCService::add_method("FileQuery",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::FileQuery);
		});

	this->srpc::RPCService::add_method("FileUpload",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::FileUpload);
		});

	this->srpc::RPCService::add_method("UploadInit",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::UploadInit);
		});

	this->srpc::RPCService::add_method("UploadChunk",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::UploadChunk);
		});

	this->srpc::RPCService::add_method("UploadComplete",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::UploadComplete);
		});

	this->srpc::RPCService::add_method("UploadStatus",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::UploadStatus);
		});

	this->srpc::RPCService::add_method("FileDownload",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::FileDownload);
		});

	this->srpc::RPCService::add_method("FileDelete",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::FileDelete);
		});

	this->srpc::RPCService::add_method("FileRename",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::FileRename);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("webdisk.FileService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("webdisk.FileService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::FileQuery(const FileQueryReq *req, FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("FileQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> SRPCClient::async_FileQuery(const FileQueryReq *req)
{
	using RESULT = std::pair<FileQueryResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileQueryResp>("FileQuery", srpc::RPCAsyncFutureCallback<FileQueryResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::FileUpload(const FileUploadReq *req, FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("FileUpload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileUpload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> SRPCClient::async_FileUpload(const FileUploadReq *req)
{
	using RESULT = std::pair<FileUploadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileUploadResp>("FileUpload", srpc::RPCAsyncFutureCallback<FileUploadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::UploadInit(const UploadInitReq *req, UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("UploadInit", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadInit(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> SRPCClient::async_UploadInit(const UploadInitReq *req)
{
	using RESULT = std::pair<UploadInitResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadInitResp>("UploadInit", srpc::RPCAsyncFutureCallback<UploadInitResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("UploadChunk", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadChunk(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> SRPCClient::async_UploadChunk(const UploadChunkReq *req)
{
	using RESULT = std::pair<UploadChunkResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadChunkResp>("UploadChunk", srpc::RPCAsyncFutureCallback<UploadChunkResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("UploadComplete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadComplete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> SRPCClient::async_UploadComplete(const UploadCompleteReq *req)
{
	using RESULT = std::pair<UploadCompleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadCompleteResp>("UploadComplete", srpc::RPCAsyncFutureCallback<UploadCompleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("UploadStatus", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadStatus(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> SRPCClient::async_UploadStatus(const UploadStatusReq *req)
{
	using RESULT = std::pair<UploadStatusResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadStatusResp>("UploadStatus", srpc::RPCAsyncFutureCallback<UploadStatusResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("FileDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> SRPCClient::async_FileDownload(const FileDownloadReq *req)
{
	using RESULT = std::pair<FileDownloadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDownloadResp>("FileDownload", srpc::RPCAsyncFutureCallback<FileDownloadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("FileDelete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDelete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> SRPCClient::async_FileDelete(const FileDeleteReq *req)
{
	using RESULT = std::pair<FileDeleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDeleteResp>("FileDelete", srpc::RPCAsyncFutureCallback<FileDeleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::FileRename(const FileRenameReq *req, FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("FileRename", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileRename(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> SRPCClient::async_FileRename(const FileRenameReq *req)
{
	using RESULT = std::pair<FileRenameResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileRenameResp>("FileRename", srpc::RPCAsyncFutureCallback<FileRenameResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_FileQuery_task(FileQueryDone done)
{
	return this->create_rpc_client_task("FileQuery", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_FileUpload_task(FileUploadDone done)
{
	return this->create_rpc_client_task("FileUpload", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_UploadInit_task(UploadInitDone done)
{
	return this->create_rpc_client_task("UploadInit", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_UploadChunk_task(UploadChunkDone done)
{
	return this->create_rpc_client_task("UploadChunk", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_UploadComplete_task(UploadCompleteDone done)
{
	return this->create_rpc_client_task("UploadComplete", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_UploadStatus_task(UploadStatusDone done)
{
	return this->create_rpc_client_task("UploadStatus", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_FileDownload_task(FileDownloadDone done)
{
	return this->create_rpc_client_task("FileDownload", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_FileDelete_task(FileDeleteDone done)
{
	return this->create_rpc_client_task("FileDelete", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_FileRename_task(FileRenameDone done)
{
	return this->create_rpc_client_task("FileRename", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("webdisk/FileService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("webdisk/FileService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::FileQuery(const FileQueryReq *req, FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("FileQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> SRPCHttpClient::async_FileQuery(const FileQueryReq *req)
{
	using RESULT = std::pair<FileQueryResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileQueryResp>("FileQuery", srpc::RPCAsyncFutureCallback<FileQueryResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::FileUpload(const FileUploadReq *req, FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("FileUpload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileUpload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> SRPCHttpClient::async_FileUpload(const FileUploadReq *req)
{
	using RESULT = std::pair<FileUploadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileUploadResp>("FileUpload", srpc::RPCAsyncFutureCallback<FileUploadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::UploadInit(const UploadInitReq *req, UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("UploadInit", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadInit(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> SRPCHttpClient::async_UploadInit(const UploadInitReq *req)
{
	using RESULT = std::pair<UploadInitResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadInitResp>("UploadInit", srpc::RPCAsyncFutureCallback<UploadInitResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::UploadChunk(const UploadChunkReq *req, UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("UploadChunk", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadChunk(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> SRPCHttpClient::async_UploadChunk(const UploadChunkReq *req)
{
	using RESULT = std::pair<UploadChunkResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadChunkResp>("UploadChunk", srpc::RPCAsyncFutureCallback<UploadChunkResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("UploadComplete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadComplete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> SRPCHttpClient::async_UploadComplete(const UploadCompleteReq *req)
{
	using RESULT = std::pair<UploadCompleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadCompleteResp>("UploadComplete", srpc::RPCAsyncFutureCallback<UploadCompleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::UploadStatus(const UploadStatusReq *req, UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("UploadStatus", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadStatus(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> SRPCHttpClient::async_UploadStatus(const UploadStatusReq *req)
{
	using RESULT = std::pair<UploadStatusResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadStatusResp>("UploadStatus", srpc::RPCAsyncFutureCallback<UploadStatusResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::FileDownload(const FileDownloadReq *req, FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("FileDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> SRPCHttpClient::async_FileDownload(const FileDownloadReq *req)
{
	using RESULT = std::pair<FileDownloadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDownloadResp>("FileDownload", srpc::RPCAsyncFutureCallback<FileDownloadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::FileDelete(const FileDeleteReq *req, FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("FileDelete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDelete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> SRPCHttpClient::async_FileDelete(const FileDeleteReq *req)
{
	using RESULT = std::pair<FileDeleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDeleteResp>("FileDelete", srpc::RPCAsyncFutureCallback<FileDeleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::FileRename(const FileRenameReq *req, FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("FileRename", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileRename(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> SRPCHttpClient::async_FileRename(const FileRenameReq *req)
{
	using RESULT = std::pair<FileRenameResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileRenameResp>("FileRename", srpc::RPCAsyncFutureCallback<FileRenameResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_FileQuery_task(FileQueryDone done)
{
	return this->create_rpc_client_task("FileQuery", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_FileUpload_task(FileUploadDone done)
{
	return this->create_rpc_client_task("FileUpload", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_UploadInit_task(UploadInitDone done)
{
	return this->create_rpc_client_task("UploadInit", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_UploadChunk_task(UploadChunkDone done)
{
	return this->create_rpc_client_task("UploadChunk", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_UploadComplete_task(UploadCompleteDone done)
{
	return this->create_rpc_client_task("UploadComplete", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_UploadStatus_task(UploadStatusDone done)
{
	return this->create_rpc_client_task("UploadStatus", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_FileDownload_task(FileDownloadDone done)
{
	return this->create_rpc_client_task("FileDownload", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_FileDelete_task(FileDeleteDone done)
{
	return this->create_rpc_client_task("FileDelete", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_FileRename_task(FileRenameDone done)
{
	return this->create_rpc_client_task("FileRename", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("webdisk.FileService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("webdisk.FileService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::FileQuery(const FileQueryReq *req, FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("FileQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> BRPCClient::async_FileQuery(const FileQueryReq *req)
{
	using RESULT = std::pair<FileQueryResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileQueryResp>("FileQuery", srpc::RPCAsyncFutureCallback<FileQueryResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::FileUpload(const FileUploadReq *req, FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("FileUpload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileUpload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> BRPCClient::async_FileUpload(const FileUploadReq *req)
{
	using RESULT = std::pair<FileUploadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileUploadResp>("FileUpload", srpc::RPCAsyncFutureCallback<FileUploadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::UploadInit(const UploadInitReq *req, UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("UploadInit", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadInit(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> BRPCClient::async_UploadInit(const UploadInitReq *req)
{
	using RESULT = std::pair<UploadInitResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadInitResp>("UploadInit", srpc::RPCAsyncFutureCallback<UploadInitResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("UploadChunk", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadChunk(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> BRPCClient::async_UploadChunk(const UploadChunkReq *req)
{
	using RESULT = std::pair<UploadChunkResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadChunkResp>("UploadChunk", srpc::RPCAsyncFutureCallback<UploadChunkResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("UploadComplete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadComplete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> BRPCClient::async_UploadComplete(const UploadCompleteReq *req)
{
	using RESULT = std::pair<UploadCompleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadCompleteResp>("UploadComplete", srpc::RPCAsyncFutureCallback<UploadCompleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("UploadStatus", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadStatus(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> BRPCClient::async_UploadStatus(const UploadStatusReq *req)
{
	using RESULT = std::pair<UploadStatusResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadStatusResp>("UploadStatus", srpc::RPCAsyncFutureCallback<UploadStatusResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("FileDownload", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> BRPCClient::async_FileDownload(const FileDownloadReq *req)
{
	using RESULT = std::pair<FileDownloadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDownloadResp>("FileDownload", srpc::RPCAsyncFutureCallback<FileDownloadResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("FileDelete", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDelete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> BRPCClient::async_FileDelete(const FileDeleteReq *req)
{
	using RESULT = std::pair<FileDeleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDeleteResp>("FileDelete", srpc::RPCAsyncFutureCallback<FileDeleteResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::FileRename(const FileRenameReq *req, FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("FileRename", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileRename(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> BRPCClient::async_FileRename(const FileRenameReq *req)
{
	using RESULT = std::pair<FileRenameResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileRenameResp>("FileRename", srpc::RPCAsyncFutureCallback<FileRenameResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_FileQuery_task(FileQueryDone done)
{
	return this->create_rpc_client_task("FileQuery", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_FileUpload_task(FileUploadDone done)
{
	return this->create_rpc_client_task("FileUpload", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_UploadInit_task(UploadInitDone done)
{
	return this->create_rpc_client_task("UploadInit", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_UploadChunk_task(UploadChunkDone done)
{
	return this->create_rpc_client_task("UploadChunk", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_UploadComplete_task(UploadCompleteDone done)
{
	return this->create_rpc_client_task("UploadComplete", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_UploadStatus_task(UploadStatusDone done)
{
	return this->create_rpc_client_task("UploadStatus", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_FileDownload_task(FileDownloadDone done)
{
	return this->create_rpc_client_task("FileDownload", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_FileDelete_task(FileDeleteDone done)
{
	return this->create_rpc_client_task("FileDelete", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_FileRename_task(FileRenameDone done)
{
	return this->create_rpc_client_task("FileRename", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("webdisk.FileService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("webdisk.FileService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::FileQuery(const FileQueryReq *req, FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> TRPCClient::async_FileQuery(const FileQueryReq *req)
{
	using RESULT = std::pair<FileQueryResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileQueryResp>("/webdisk.FileService/FileQuery", srpc::RPCAsyncFutureCallback<FileQueryResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::FileUpload(const FileUploadReq *req, FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileUpload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileUpload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> TRPCClient::async_FileUpload(const FileUploadReq *req)
{
	using RESULT = std::pair<FileUploadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileUploadResp>("/webdisk.FileService/FileUpload", srpc::RPCAsyncFutureCallback<FileUploadResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::UploadInit(const UploadInitReq *req, UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadInit", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadInit(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> TRPCClient::async_UploadInit(const UploadInitReq *req)
{
	using RESULT = std::pair<UploadInitResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadInitResp>("/webdisk.FileService/UploadInit", srpc::RPCAsyncFutureCallback<UploadInitResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadChunk", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadChunk(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> TRPCClient::async_UploadChunk(const UploadChunkReq *req)
{
	using RESULT = std::pair<UploadChunkResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadChunkResp>("/webdisk.FileService/UploadChunk", srpc::RPCAsyncFutureCallback<UploadChunkResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadComplete", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadComplete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> TRPCClient::async_UploadComplete(const UploadCompleteReq *req)
{
	using RESULT = std::pair<UploadCompleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadCompleteResp>("/webdisk.FileService/UploadComplete", srpc::RPCAsyncFutureCallback<UploadCompleteResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadStatus", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadStatus(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> TRPCClient::async_UploadStatus(const UploadStatusReq *req)
{
	using RESULT = std::pair<UploadStatusResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadStatusResp>("/webdisk.FileService/UploadStatus", srpc::RPCAsyncFutureCallback<UploadStatusResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileDownload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> TRPCClient::async_FileDownload(const FileDownloadReq *req)
{
	using RESULT = std::pair<FileDownloadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDownloadResp>("/webdisk.FileService/FileDownload", srpc::RPCAsyncFutureCallback<FileDownloadResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileDelete", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDelete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> TRPCClient::async_FileDelete(const FileDeleteReq *req)
{
	using RESULT = std::pair<FileDeleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDeleteResp>("/webdisk.FileService/FileDelete", srpc::RPCAsyncFutureCallback<FileDeleteResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::FileRename(const FileRenameReq *req, FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileRename", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileRename(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> TRPCClient::async_FileRename(const FileRenameReq *req)
{
	using RESULT = std::pair<FileRenameResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileRenameResp>("/webdisk.FileService/FileRename", srpc::RPCAsyncFutureCallback<FileRenameResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_FileQuery_task(FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_FileUpload_task(FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileUpload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_UploadInit_task(UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadInit", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_UploadChunk_task(UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadChunk", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_UploadComplete_task(UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadComplete", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_UploadStatus_task(UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/UploadStatus", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_FileDownload_task(FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileDownload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_FileDelete_task(FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileDelete", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_FileRename_task(FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("/webdisk.FileService/FileRename", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("webdisk.FileService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("webdisk.FileService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::FileQuery(const FileQueryReq *req, FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("FileQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::FileQuery(const FileQueryReq *req, FileQueryResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileQueryResp, srpc::RPCSyncContext>> TRPCHttpClient::async_FileQuery(const FileQueryReq *req)
{
	using RESULT = std::pair<FileQueryResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileQueryResp>("FileQuery", srpc::RPCAsyncFutureCallback<FileQueryResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::FileUpload(const FileUploadReq *req, FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("FileUpload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::FileUpload(const FileUploadReq *req, FileUploadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileUpload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileUploadResp, srpc::RPCSyncContext>> TRPCHttpClient::async_FileUpload(const FileUploadReq *req)
{
	using RESULT = std::pair<FileUploadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileUploadResp>("FileUpload", srpc::RPCAsyncFutureCallback<FileUploadResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::UploadInit(const UploadInitReq *req, UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("UploadInit", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::UploadInit(const UploadInitReq *req, UploadInitResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadInit(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadInitResp, srpc::RPCSyncContext>> TRPCHttpClient::async_UploadInit(const UploadInitReq *req)
{
	using RESULT = std::pair<UploadInitResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadInitResp>("UploadInit", srpc::RPCAsyncFutureCallback<UploadInitResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::UploadChunk(const UploadChunkReq *req, UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("UploadChunk", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::UploadChunk(const UploadChunkReq *req, UploadChunkResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadChunk(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadChunkResp, srpc::RPCSyncContext>> TRPCHttpClient::async_UploadChunk(const UploadChunkReq *req)
{
	using RESULT = std::pair<UploadChunkResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadChunkResp>("UploadChunk", srpc::RPCAsyncFutureCallback<UploadChunkResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("UploadComplete", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::UploadComplete(const UploadCompleteReq *req, UploadCompleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadComplete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadCompleteResp, srpc::RPCSyncContext>> TRPCHttpClient::async_UploadComplete(const UploadCompleteReq *req)
{
	using RESULT = std::pair<UploadCompleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadCompleteResp>("UploadComplete", srpc::RPCAsyncFutureCallback<UploadCompleteResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::UploadStatus(const UploadStatusReq *req, UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("UploadStatus", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::UploadStatus(const UploadStatusReq *req, UploadStatusResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_UploadStatus(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UploadStatusResp, srpc::RPCSyncContext>> TRPCHttpClient::async_UploadStatus(const UploadStatusReq *req)
{
	using RESULT = std::pair<UploadStatusResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UploadStatusResp>("UploadStatus", srpc::RPCAsyncFutureCallback<UploadStatusResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::FileDownload(const FileDownloadReq *req, FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("FileDownload", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::FileDownload(const FileDownloadReq *req, FileDownloadResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDownload(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDownloadResp, srpc::RPCSyncContext>> TRPCHttpClient::async_FileDownload(const FileDownloadReq *req)
{
	using RESULT = std::pair<FileDownloadResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDownloadResp>("FileDownload", srpc::RPCAsyncFutureCallback<FileDownloadResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::FileDelete(const FileDeleteReq *req, FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("FileDelete", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::FileDelete(const FileDeleteReq *req, FileDeleteResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileDelete(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileDeleteResp, srpc::RPCSyncContext>> TRPCHttpClient::async_FileDelete(const FileDeleteReq *req)
{
	using RESULT = std::pair<FileDeleteResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileDeleteResp>("FileDelete", srpc::RPCAsyncFutureCallback<FileDeleteResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::FileRename(const FileRenameReq *req, FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("FileRename", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::FileRename(const FileRenameReq *req, FileRenameResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_FileRename(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<FileRenameResp, srpc::RPCSyncContext>> TRPCHttpClient::async_FileRename(const FileRenameReq *req)
{
	using RESULT = std::pair<FileRenameResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<FileRenameResp>("FileRename", srpc::RPCAsyncFutureCallback<FileRenameResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_FileQuery_task(FileQueryDone done)
{
	auto *task = this->create_rpc_client_task("FileQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_FileUpload_task(FileUploadDone done)
{
	auto *task = this->create_rpc_client_task("FileUpload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_UploadInit_task(UploadInitDone done)
{
	auto *task = this->create_rpc_client_task("UploadInit", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_UploadChunk_task(UploadChunkDone done)
{
	auto *task = this->create_rpc_client_task("UploadChunk", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_UploadComplete_task(UploadCompleteDone done)
{
	auto *task = this->create_rpc_client_task("UploadComplete", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_UploadStatus_task(UploadStatusDone done)
{
	auto *task = this->create_rpc_client_task("UploadStatus", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_FileDownload_task(FileDownloadDone done)
{
	auto *task = this->create_rpc_client_task("FileDownload", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_FileDelete_task(FileDeleteDone done)
{
	auto *task = this->create_rpc_client_task("FileDelete", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_FileRename_task(FileRenameDone done)
{
	auto *task = this->create_rpc_client_task("FileRename", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace FileService

} // end namespace webdisk

